name: entertainmethub
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.4







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - .env

